using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared._Sich.Hunter;
using Robust.Shared.Maths;

namespace Content.Client._Sich.Hunter;

public sealed partial class HunterCrewWindow : DefaultWindow
{
    private BoxContainer HunterList => FindControl<BoxContainer>("HunterList");

    public HunterCrewWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(HunterConsoleState state)
    {
        HunterList.RemoveAllChildren();

        for (int i = 0; i < state.Hunters.Count; i++)
        {
            var hunter = state.Hunters[i];
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(4)
            };

            row.AddChild(new Label { Text = (i + 1).ToString(), MinWidth = 30, FontColorOverride = Color.Gray });
            row.AddChild(new Label { Text = hunter.Name, HorizontalExpand = true, FontColorOverride = Color.FromHex("#E5B107") });
            
            var statusColor = hunter.Status switch {
                "Живий" => Color.FromHex("#32CD32"),
                "Критичний" => Color.FromHex("#FF4500"),
                "Мертвий" => Color.FromHex("#8B0000"),
                _ => Color.Gray
            };
            row.AddChild(new Label { Text = hunter.Status, MinWidth = 100, FontColorOverride = statusColor });
            row.AddChild(new Label { Text = hunter.Position, MinWidth = 120, FontColorOverride = Color.FromHex("#D3D3D3") });

            HunterList.AddChild(row);
        }
    }
}
