using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Content.Client._RMC14.Vendors;

namespace Content.Client._Sich.Hunter;

[GenerateTypedNameReferences]
public sealed partial class SichHunterVendorPanel : Control
{
    public static readonly Color YautjaColor = Color.FromHex("#700303");
    public static readonly Color YautjaBorderColor = Color.Black;
    public static readonly Color YautjaHoveredColor = Color.FromHex("#A00303");
    private static readonly Color DisabledColor = Color.FromHex("#440000");

    public Color Color = YautjaColor;
    public Color BorderColor = YautjaBorderColor;
    public Color HoveredColor = YautjaHoveredColor;

    public SichHunterVendorPanel()
    {
        RobustXamlLoader.Load(this);

        Button.OnDrawModeChanged += UpdateColor;
        UpdateColor();
    }

    private void UpdateColor()
    {
        if (Panel.PanelOverride == null)
            Panel.PanelOverride = new StyleBoxFlat();

        if (Panel.PanelOverride is not StyleBoxFlat panel)
            return;

        // Ensure the button itself is also styled or transparent
        Button.StyleBoxOverride = panel;
        Button.Label.FontColorOverride = Color.White;

        if (Button.Disabled)
            panel.BackgroundColor = DisabledColor;
        else
            panel.BackgroundColor = Button.IsHovered ? HoveredColor : Color;

        panel.BorderColor = BorderColor;
        panel.BorderThickness = new Thickness(1);
    }



    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateColor();
    }
}
