using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sich.Hunter;

[GenerateTypedNameReferences]
public sealed partial class SichHunterVendorWindow : DefaultWindow
{
    public SichHunterVendorWindow()
    {
        RobustXamlLoader.Load(this);

        Background.PanelOverride = new StyleBoxFlat(Color.FromHex("#300303"));
        Search.StyleBoxOverride = new StyleBoxFlat(Color.Black);
        Title = "Yautja Hunting Gear Rack";
    }
}
