using Content.Shared._RMC14.Vendors;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sich.Hunter;

[GenerateTypedNameReferences]
public sealed partial class SichHunterVendorSection : Control
{
    public CMVendorSection? Section;

    public SichHunterVendorSection()
    {
        RobustXamlLoader.Load(this);

        Header.PanelOverride = new StyleBoxFlat(Color.Black);
    }
}

