using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sich.Hunter;

[GenerateTypedNameReferences]
public sealed partial class SichHunterVendorEntry : Control
{
    public SichHunterVendorEntry()
    {
        RobustXamlLoader.Load(this);
    }
}
