- type: entity
  abstract: true
  id: HuntTechBase
  name: Стійка спорядження мисливця
  placement:
    mode: SnapgridCenter
  components:
  - type: Transform
    anchored: true
    noRot: true
  - type: Clickable
  - type: InteractionOutline
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,1.45"
        density: 200
        mask:
        - MachineMask
        layer:
        - MachineLayer
  - type: Tag
    tags:
    - Structure
  - type: UserInterface
    interfaces:
      enum.CMAutomatedVendorUI.Key:
        type: CMAutomatedVendorBui
  - type: ActivatableUI
    key: enum.CMAutomatedVendorUI.Key
  - type: ActivatableUIRequiresAccess
  - type: WallMount
    arc: 360
  - type: InteractedBlacklist
    blacklist:
      components:
      - Xeno
  - type: RMCMesonsNonviewable

- type: entity
  abstract: true
  parent: HuntTechBase
  id: HuntTechBaseAnchorable
  components:
  - type: Transform
    anchored: true
  - type: Anchorable
  - type: Pullable
  - type: Physics
    bodyType: Static
  - type: Damageable
    damageContainer: StructuralMarine
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 500
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,1.45"
        density: 200
        mask:
        - MachineMask
        layer:
        - MachineLayer
        - BulletImpassable