using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._Sich.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class HunterTranslatorWindow : DefaultWindow
{
    public event Action<string>? OnSendMessage;

    public HunterTranslatorWindow()
    {
        RobustXamlLoader.Load(this);

        SendButton.OnPressed += _ => SendMessage();
        MessageLineEdit.OnTextEntered += _ => SendMessage();
    }

    private void SendMessage()
    {
        if (string.IsNullOrWhiteSpace(MessageLineEdit.Text))
            return;

        OnSendMessage?.Invoke(MessageLineEdit.Text);
        MessageLineEdit.Text = string.Empty;
        Close();
    }

    protected override void Opened()
    {
        base.Opened();
        MessageLineEdit.GrabKeyboardFocus();
    }
}
