- type: job
  parent: RMCCLFCellLeader
  id: SichCLFCellLeader
  startingGear: SichGearCLFCellLeader
  spawnMenuRoleName: ФВК Лідер
  accessGroups:
  - Colony
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillFireman: 3
        RMCSkillMeleeWeapons: 1
        RMCSkillPolice: 1
        RMCSkillEndurance: 5
        RMCSkillJtac: 3
        RMCSkillVehicles: 1

        RMCSkillConstruction: 2
        RMCSkillEngineer: 2
        RMCSkillPowerLoader: 2
        RMCSkillMedical: 2
        RMCSkillSurgery: 1

        RMCSkillOverwatch: 1
        RMCSkillLeadership: 3
        RMCSkillCqc: 2
    - type: NpcFactionMember
      factions:
      - CLF
    - type: JobPrefix
      prefix: rmc-job-prefix-clf-cell-leader
    - type: SquadLeader
      icon:
        sprite: _RMC14/Interface/cm_job_icons.rsi
        state: clf_sl
    - type: RMCPointing
    - type: MarineOrders
  hidden: true

- type: entity
  id: SichRandomHumanoidCLFCellLeader
  name: ФВК спавнер ролі привидів Лідера
  suffix: Spawner, Player
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Accessory/Armbands/clf_armband.rsi
    state: icon
  - type: RandomHumanoidSpawner
    settings: SichCLFCellLeader

- type: randomHumanoidSettings
  parent: RMCEventHumanoid
  id: SichCLFCellLeader
  components:
  - type: GhostRole
    name: rmc-ghost-role-clf-cell-leader
    description: rmc-ghost-role-information-clf-description
    rules: rmc-ghost-role-information-clf-rules
    reregister: false
    job: SichCLFCellLeader
    raffle:
      settings: short
    requirements:
    - !type:RoleTimeRequirement
      role: CMJobSquadLeader
      time: 18000 # 5 Hours
  - type: GhostRoleApplySpecial
    squad: SquadCLF

- type: startingGear
  id: SichGearCLFCellLeader
  equipment:
    head: RMCHeadBeretOfficerHos
    mask: RMCCombatUtilityKnifeB # TODO RMC14 Type 80 bayonet
    ears: RMCHeadsetDistressCLF
    ears2: CMScrewdriver
    eyes: RMCSunglassesBig
    jumpsuit: RMCJumpsuitCLFWebbingMAR50
    outerClothing: SichCoatMilitia
    gloves: RMCHandsVeteranPMC
    shoes: RMCBootsPMC
    suitstorage: RMCWeaponRifleMAR30
    id: SichIDCardCLFCellLeader # TODO RMC14
    belt: RMCMAR40BeltFilled
    back: RMCSatchelLightpack
    pocket1: RMCFlashlight
    pocket2: RMCPouchMedkit
  storage:
      jumpsuit:
      - CMCrowbar
      - CMWrench
      - CMMultitool
      - RMCExplosivePlastic
      - RMCExplosivePlastic
      back:
      - RMCGrenadeMolotov
      - CMPacketGrenadeFragOldFilled
      - RMCRangefinder
      - RMCWeaponPistolHandcannon
      - RMCMagazinePistolHandcannon
      - RMCMagazinePistolHandcannon
      - RMCBoxClaymoreMineFilled
      - RMCBoxClaymoreMineFilled
      outerClothing:
      - RMCMagazineRifleMAR40Ext
      - RMCMagazineRifleMAR40Ext
      pocket2:
      - CMSurgicalLine
      - CMSynthGraft
      - CMBloodPackFull
      - CMHealthAnalyzer
      - CMPillCanisterKelotane
      - CMPillCanisterBicaridine
      - CMRollerBedSpawnFolded
