- type: rank
  id: RMCRankWeYaJuniorExecutive
  name: Молодший керівник
  prefix: Мол.Кер.

- type: rank
  id: RMCRankWeYaExecutive
  name: Керівник
  prefix: Кер.

- type: rank
  id: RMCRankWeYaSeniorExecutive
  name: Старший керівник
  prefix: Старш.Кер.

- type: rank
  id: RMCRankWeYaExecutiveSpecialist
  name: Спеціаліст з керівних питань
  prefix: Спец-з-Кер.пит.
  paygrade: WYC5

- type: rank
  id: RMCRankWeYaExecutiveSupervisor
  name: Інспектор з керівних питань
  prefix: Інсп-з-Кер.пит.
  paygrade: WYC6

- type: rank
  id: RMCRankWeYaAssistantManager
  name: Помічник менеджера
  prefix: Помін.Мен.

- type: rank
  id: RMCRankWeYaDivisionManager
  name: Керівник відділу
  prefix: Кер.Від.

- type: rank
  id: RMCRankWeYaChiefExecutive
  name: Головний керівник
  prefix: Гол.Кер.

- type: rank
  id: RMCRankWeYaDeputyDirector
  name: Заступник директора
  prefix: Заст. Директора

- type: rank
  id: RMCRankWeYaDirector
  name: Директор
  prefix: Директор

# Lawyers
- type: rank
  id: RMCRankWeYaLegalSpecialist
  name: Юридичний спеціаліст
  prefix: Юр.Спец.

- type: rank
  id: RMCRankWeYaLegalSupervisor
  name: Юридичний інспектор
  prefix: Юр.Інсп.
